[getList]
SELECT c.*,u.NAME,u.GENDER,u.TITLE,d.DEPTNAME FROM CHECKINOUT c
INNER JOIN USERINFO u ON u.USERID = c.USERID
INNER JOIN DEPARTMENTS d ON d.DEPTID = u.DEFAULTDEPTID
WHERE (u.NAME LIKE $P{searchtext}
OR u.TITLE LIKE $P{searchtext}
OR c.BRN LIKE $P{searchtext})
AND c.CHECKTIME BETWEEN $P{dtfrom} AND $P{dtto}

[removeLog]
DELETE FROM CHECKINOUT WHERE BRN = $P{BRN}

