[getList]
SELECT c.*,l.LeaveName,u.NAME,u.GENDER,u.TITLE,d.DEPTNAME FROM USER_SPEDAY c
INNER JOIN USERINFO u ON u.USERID = c.USERID
INNER JOIN DEPARTMENTS d ON d.DEPTID = u.DEFAULTDEPTID
INNER JOIN LeaveClass l ON l.LeaveId = c.DATEID
WHERE (u.NAME LIKE $P{searchtext}
OR u.TITLE LIKE $P{searchtext}
OR l.LeaveName LIKE $P{searchtext}
OR c.BRN LIKE $P{searchtext})
AND c.STARTSPECDAY BETWEEN $P{dtfrom} AND $P{dtto}

[removeLog]
DELETE FROM USER_SPEDAY WHERE BRN = $P{BRN}

